// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOLfGNOXKvGHzRucT0J1VgZsedAl--omI',
    appId: '1:94378825137:web:c7849a35b2c9e43c239990',
    messagingSenderId: '94378825137',
    projectId: 'we-chat-9a80e',
    authDomain: 'we-chat-9a80e.firebaseapp.com',
    storageBucket: 'we-chat-9a80e.appspot.com',
    measurementId: 'G-FQ3KB0M34N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq2LcUfKnHboRrvobAgborG62RfrrFHEU',
    appId: '1:94378825137:android:40a7453337dc76d3239990',
    messagingSenderId: '94378825137',
    projectId: 'we-chat-9a80e',
    storageBucket: 'we-chat-9a80e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-1GztD63FRZQDSxoyb_rhrjvyut7uhNM',
    appId: '1:94378825137:ios:cf55c13896322217239990',
    messagingSenderId: '94378825137',
    projectId: 'we-chat-9a80e',
    storageBucket: 'we-chat-9a80e.appspot.com',
    androidClientId: '94378825137-4l4e6rulrm26jt5ovt7jh7mn6oe2i9fp.apps.googleusercontent.com',
    iosClientId: '94378825137-d5d25rthr6tt5sjgi42e5gq0flkvvksh.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
